### ISSUE TITLE
Confusion around `launchParams` in explainer

### ISSUE THREAD

**Issue by alice** [WICG/file-handling#36] opened 2019-12-03 22:53 UTC
Coming here from via https://github.com/w3ctag/design-reviews/issues/371. 

The explainer says:

> Note: The `launchParams` property is discussed in more detail in the [Launch Events](https://github.com/WICG/sw-launch/issues/20) explainer.

That links to an issue on [sw-launch](https://github.com/WICG/sw-launch/), rather than the explainer, and the `launchParams` property doesn't seem to get a mention in the explainer. Is there a more in-depth explanation of that property somewhere other than in the issue thread? Is the explainer mid-update?

**Comment by mgiuca** [comment] 2019-12-05 02:14
Thanks @alice. Duplicate of #34 where I was planning to make this relationship between the two specs more clear.

**Closed by mgiuca** 2019-12-05 02:14 UTC
